document.writeln("<section style=\'background-color: black;padding-bottom: 50px\'>");
document.writeln("				<div class=\'over\'>");
document.writeln("					<div class=\'over_bg\'>");
document.writeln("					</div>");
document.writeln("					<div class=\'over_t_bg\'>");
document.writeln("						<address class=\'over_div1\'>");
document.writeln("							<p>版权所有：东箭完整家居▪e键美家 浙ICP备15039099号-2</p>");
document.writeln("							<p>地址：杭州市富阳区东洲工业园区东望路与十三号路交叉口</p>");
document.writeln("							<p>电话：086-0571-86089292</p>");
document.writeln("							<p>&nbsp;</p>");
document.writeln("						</address>");
document.writeln("						<nav class=\'over_div2\'>");
document.writeln("							<ul>");
document.writeln("								<li><a href=\'javascript:void(0);\'>购物指南</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>购物流程</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>关于服务</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>关于整包</a></li>");
document.writeln("							</ul>");
document.writeln("							<ul>");
document.writeln("								<li><a href=\'javascript:void(0);\'>配送服务</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>收费标准</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>关于安装</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>到货时间</a></li>");
document.writeln("							</ul>");
document.writeln("							<ul>");
document.writeln("								<li><a href=\'javascript:void(0);\'>支付方式</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>在线支付</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>微信支付</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>货到付款</a></li>");
document.writeln("							</ul>");
document.writeln("							<ul>");
document.writeln("								<li><a href=\'javascript:void(0);\'>售后服务</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>退款政策</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>退款说明</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>常见问题</a></li>");
document.writeln("							</ul>");
document.writeln("							<ul>");
document.writeln("								<li><a href=\'javascript:void(0);\'>联系我们</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>联系我们</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>全国门店</a></li>");
document.writeln("								<li><a href=\'javascript:void(0);\'>人才招聘</a></li>");
document.writeln("							</ul>");
document.writeln("						</nav>");
document.writeln("						<div class=\'over_div3\'>");
document.writeln("							<a href=\'#\'>e键美家</a>");
document.writeln("							<img src=\'../images/index_Xf_show.jpg\' alt=\'\'>");
document.writeln("							<p>官方微信</p>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("			</section>");