document.writeln("<!--第一部分-->");
document.writeln("		     <section class=\'black_section\'>");
document.writeln("		          <div id=\'black\'>");
document.writeln("		               <div class=\'black_left\'>");
document.writeln("		                   <img src=\'../images/site.png\' alt=\'\' >");
document.writeln("		                   <span>所在城市</span>");
document.writeln("		                   <span>杭州</span>");
document.writeln("		               </div>");
document.writeln("		               <div class=\'black_right\'>");
document.writeln("		                   <span>欢迎来到e键美家</span>");
document.writeln("		                   <a href=\'../html/null.html\' >登入</a>");
document.writeln("		                   <a href=\'../html/null.html\' >注册</a>");
document.writeln("		               </div>");
document.writeln("		          </div>");
document.writeln("		     </section>");
document.writeln("		     <!--第二部分导航-->");
document.writeln("	 		<section>");
document.writeln("		         <div class=\'nav\'>");
document.writeln("		             <div class=\'ej\'>");
document.writeln("		                <a href=\'../html/index.html\'><img src=\'../images/ej.png\' alt=\'e键美家\'></a>");
document.writeln("		                 <span class=\'span1\'>做最爽快的家装!</span>");
document.writeln("		             </div>");
document.writeln("		             <div class=\'relation\'>");
document.writeln("		                 <img src=\'../images/phone.png\' alt=\'电话热线\'>");
document.writeln("		                 <img src=\'../images/_01.png\' alt=\'\'>");
document.writeln("		                 <div class=\'finger\'>");
document.writeln("		                     <img src=\'../images/finger.png\' alt=\'二维码\'>");
document.writeln("		                     <span>关注微博</span>");
document.writeln("		                 </div>");
document.writeln("		                 <div class=\'rwm\'>");
document.writeln("		                     <img src=\'../images/wechat.png\' alt=\'二维码\'>");
document.writeln("		                     <span>关注微信</span>");
document.writeln("		                 </div>");
document.writeln("		");
document.writeln("		             </div>");
document.writeln("		             <div class=\'nav_a\'>");
document.writeln("						 <a href=\'../html/index.html\'>首页</a>");
document.writeln("		                 <a href=\'../html/package.html\'>e键套餐</a>");
document.writeln("		                 <a href=\'../html/Pj_house.html\'>量房/设计 <span class=\'span_a\'>免费</span></a>");
document.writeln("		                 <a href=\'../html/null.html\'>施工现场</a>");
document.writeln("		                 <a href=\'../html/null.html\'>工长店铺</a>");
document.writeln("		                 <a href=\'../html/null.html\'>设计师店铺</a>");
document.writeln("		                 <a href=\'../html/class.html\'>美家课堂</a>");
document.writeln("		                 <a href=\'../html/experience.html\'>体验馆</a>");
document.writeln("		                 <a href=\'../html/order.html\'>我的订单</a>");
document.writeln("		                 <a href=\'../html/about_us.html\'>关于我们</a>");
document.writeln("		                 <a href=\'http://www.dongjianhome.com/\'>完整家居</a>");
document.writeln("		             </div>");
document.writeln("		         </div>");
document.writeln("		     </section>");